---
site_name: CSOR – Gouvernance & Documentation
site_author: Siegfried Sekkai
repo_url: https://github.com/5136Siegfried/csor-gestion
repo_name: GitHub
edit_uri: edit/main/
use_directory_urls: false
theme:
  name: material
  language: fr
  features:
  - navigation.expand
  - navigation.instant
  - search.suggest
  - content.code.copy
  - search.highlight
  - search.suggest
  - search.share
  palette:
  - scheme: default
    primary: teal
    accent: cyan
nav:
  - Accueil: index.md

  - Statuts:
      - Version actuelle: statuts/statuts-v1.md
      - Proposition V2: statuts/statuts-v2-proposition.md
      - Historique des amendements: statuts/historique-amendements.md

  - Règlement intérieur:
      - Texte complet: reglement_interieur/reglement-2025.md
      - Guide du vote: reglement_interieur/guide-vote.md

  - Protocoles:
      - Maraude: protocoles/maraude.md
      - Soins sanitaires: protocoles/soins_sanitaires.md
      - Gestion des conflits: protocoles/gestion_conflit.md

  - Documents:
      - Charte éthique: docs/charte_ethique.md
      - Manifeste: docs/manifeste.md
      - Formulaire d'adhésion: docs/formulaire_adhesion.md

  - Assemblées:
      - Convocations: ag/convocations/index.md
      - Comptes-rendus: ag/comptes_rendus/index.md
      - Votes: ag/votes/index.md

  - Outils:
      - Modèle de fiche projet: outils/modèle-fiche-projet.md
      - Modèle de mailing: outils/modèle-mailing.md
      - Outils numériques: outils/outils-numeriques.md

markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
- footnotes
- tables
- attr_list
- pymdownx.superfences
- pymdownx.mark
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.snippets
- pymdownx.highlight
- pymdownx.tabbed
- pymdownx.details
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/5136Siegfried
  generator: false
  copyright: © 2025 – CSOR – Tous droits réservés
extra_css:
  - assets/css/custom.css
